apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: itsbharatsaini/jmeter:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5